"""feat: add initial schema

Revision ID: f27ac01928d8
Revises: 
Create Date: 2026-09-14 18:03:25.685104
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f27ac01928d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('queixa_principal', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_pacientes_nome'), ['nome'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('procedimentos_realizados', sa.Text(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultas_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultas_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('documentos_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos_paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_paciente_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('planos_tratamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('procedimentos', sa.Text(), nullable=False),
    sa.Column('valor_total_centavos', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planos_tratamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planos_tratamento_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_tratamento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcelas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcelas_plano_id'), ['plano_id'], unique=False)

    op.create_table('registros_esterilizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('identificacao_pacote', sa.Text(), nullable=True),
    sa.Column('foto_pacote_caminho', sa.String(length=500), nullable=True),
    sa.Column('ciclo', sa.String(length=60), nullable=False),
    sa.Column('data_ciclo', sa.Date(), nullable=False),
    sa.Column('responsavel', sa.String(length=120), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('identificacao_pacote IS NOT NULL OR foto_pacote_caminho IS NOT NULL', name='ck_esterilizacao_identificacao_presente'),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_esterilizacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_esterilizacao_consulta_id'), ['consulta_id'], unique=False)

    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('forma', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_parcela_id'), ['parcela_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_parcela_id'))

    op.drop_table('pagamentos')
    with op.batch_alter_table('registros_esterilizacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_esterilizacao_consulta_id'))

    op.drop_table('registros_esterilizacao')
    with op.batch_alter_table('parcelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcelas_plano_id'))

    op.drop_table('parcelas')
    with op.batch_alter_table('planos_tratamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planos_tratamento_paciente_id'))

    op.drop_table('planos_tratamento')
    with op.batch_alter_table('documentos_paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_paciente_paciente_id'))

    op.drop_table('documentos_paciente')
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_consultas_data'))

    op.drop_table('consultas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_nome'))
        batch_op.drop_index(batch_op.f('ix_pacientes_cpf'))

    op.drop_table('pacientes')
    # ### end Alembic commands ###
